image: maven:3.8.5-openjdk-17

stages:
  - build
  - test
  - package
  - image-build

variables:
  DOCKER_IMAGE_NAME: backend-services-usuarios

cache:
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml

package:
  stage: package
  script:
    - mvn package
    - POM_VERSION="$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)-$(date +%Y%m%d%H%M%S)"
    - echo "$POM_VERSION" > pom_version.txt
  artifacts:
    paths:
      - target/*.jar
      - pom_version.txt

coverage:
  stage: test
  script:
    - mvn verify org.jacoco:jacoco-maven-plugin:report
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' target/site/jacoco/jacoco.csv
  coverage: '/([0-9]{1,3}.[0-9]*) % covered/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: target/site/jacoco/jacoco.xml
    paths:
      - target/site/jacoco/

docker-build:
  stage: image-build
  image: docker:latest
  services:
    - docker:dind
  dependencies:
    - package
  before_script:
    - POM_VERSION=$(cat pom_version.txt)
    - echo "The value of POM_VERSION is:$POM_VERSION"
    - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USER --password-stdin
  script:
    - docker build -t $DOCKERHUB_USER/$DOCKER_IMAGE_NAME:$POM_VERSION .
    - docker push $DOCKERHUB_USER/$DOCKER_IMAGE_NAME:$POM_VERSION
    - docker tag $DOCKERHUB_USER/$DOCKER_IMAGE_NAME:$POM_VERSION $DOCKERHUB_USER/$DOCKER_IMAGE_NAME:latest
    - docker push $DOCKERHUB_USER/$DOCKER_IMAGE_NAME:latest
  after_script:
    - docker logout
  only:
    - main