server:
  port: 8080

spring:
  application:
    name: backend-services-usuarios
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_oyma2TUk2